export const TOGGLE_FORM = 'TOGGLE_FORM';
export const TOGGLE_ADD_FORM = 'TOGGLE_ADD_FORM';
export const REQUEST_SEARCH_RESULTS = 'REQUEST_SEARCH_RESULTS';
export const GET_RESULTS_SUCCESS = 'GET_RESULTS_SUCCESS';
export const GET_RESULTS_FAILURE = 'GET_RESULTS_FAILURE';